### ISSUE TITLE
LookupError not actually returned

### ISSUE THREAD

**Issue by jemiahlee** [hearsaycorp/richenum#41]
@rbm added a custom exception class for bad lookups, which I think is great. The problem is that it doesn't currently behave as a built-in `LookupError`, though the error message printed makes it look like it does.

If you change the test on line 76 of `test_rich_enums.py` to be:

``` python
        with self.assertRaises(LookupError):
```

instead of just using the custom class type (`EnumLookupError`), you get an error raised in the test:

```
======================================================================
ERROR: test_generic_lookup (tests.richenum.test_rich_enums.RichEnumTestSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jeremiahlee/projects/richenum/tests/richenum/test_rich_enums.py", line 77, in test_generic_lookup
    Vegetable.lookup('flavor', 'yum')
  File "/Users/jeremiahlee/projects/richenum/src/richenum/enums.py", line 284, in lookup
    % (field, value, cls)
LookupError: Could not find member matching flavor = yum in enum <class 'tests.richenum.test_rich_enums.Vegetable'>
```

This is throwing something that has a `__name__` of LookupError, but isn't actually the built-in `LookupError`, which I think is confusing to users of the library (e.g., me). I know that we could also catch `Vegetable.LookupError` (which isn't obvious from the error message above) but I think it also makes sense to allow a plain `LookupError` to be caught.

PR forthcoming.

**Comment by jemiahlee** [comment]
Solved by PR #42
